name: build
on: [ push, pull_request ]
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ g++-6, g++-8 ]
        toolset: [ gcc ]
        standard: [ c++11, c++14, gnu++14, c++1z ]
        suite: [ float128_tests ] # special_fun  distribution_tests, quadrature, float128_tests, misc, ../example/examples, ../tools ]
        include:
          - compiler: clang++-6.0
            toolset: clang
            standard: c++11
            suite: float128_tests
          - compiler: clang++-6.0
            toolset: clang
            standard: c++11
            suite: ../tools
          - compiler: clang++-6.0
            toolset: clang
            standard: c++11
            suite: ../example/examples
    steps:
      - name: Add repository
        run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
      - name: Install packages
        run: sudo apt install g++-6 g++-8 clang-6.0 libgmp-dev libmpfr-dev libfftw3-dev
      - uses: actions/checkout@v2
      - name: Checkout main boost
        run: git clone -b develop --depth 1 https://github.com/boostorg/boost.git ../boost-root
      - name: Update tools/build
        run: git submodule update --init tools/build
        working-directory: ../boost-root
      - name: Update tools/boost_install
        run: git submodule update --init tools/boost_install
        working-directory: ../boost-root
      - name: Update libs/headers
        run: git submodule update --init libs/headers
        working-directory: ../boost-root
      - name: Update libs/config
        run: git submodule update --init libs/config
        working-directory: ../boost-root
      - name: Update libs/format
        run: git submodule update --init libs/format
        working-directory: ../boost-root
      - name: Update libs/numeric
        run: git submodule update --init libs/numeric
        working-directory: ../boost-root
      - name: Update libs/type_traits
        run: git submodule update --init libs/type_traits
        working-directory: ../boost-root
      - name: Update libs/timer
        run: git submodule update --init libs/timer
        working-directory: ../boost-root
      - name: Update tools/boostdep
        run: git submodule update --init tools/boostdep
        working-directory: ../boost-root
      - name: Copy files
        run: cp -r $GITHUB_WORKSPACE/* libs/math
        working-directory: ../boost-root
      - name: Install deps
        run: python tools/boostdep/depinst/depinst.py math
        working-directory: ../boost-root
      - name: Bootstrap
        run: ./bootstrap.sh
        working-directory: ../boost-root
      - name: Generate headers
        run: ./b2 headers
        working-directory: ../boost-root
      - name: Generate user config
        run: 'echo "using ${{ matrix.toolset }} : : ${{ matrix.compiler }} : <cxxflags>-std=${{ matrix.standard }} ;" > ~/user-config.jam'
        working-directory: ../boost-root
      - name: Config info install
        run: ../../../b2 config_info_travis_install toolset=${{ matrix.toolset }}
        working-directory: ../boost-root/libs/config/test
      - name: Config info
        run: ./config_info_travis
        working-directory: ../boost-root/libs/config/test
      - name: Test
        run: ../../../b2 -j3 toolset=${{ matrix.toolset }} ${{ matrix.suite }} define=CI_SUPPRESS_KNOWN_ISSUES define=SLOW_COMPILER
        working-directory: ../boost-root/libs/math/test
